name: Link run
on: 
    push:
    pull_request: 

jobs:
    runLint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - run: npm ci 
            - run: npm run lint
            - run: echo "lint complete"
            
    runTest:
        runs-on: ubuntu-latest
        needs: runLint

        steps:
            - uses: actions/checkout@v6

            - run: npm ci
            - run: npm run test
            - run: echo "tests pass"

    runBuild:
        runs-on: ubuntu-latest
        needs: runTest

        steps:
            - uses: actions/checkout@v6
            - run: npm ci
            - run: npm run build
            - run: echo "build complete"